# -*- coding: utf-8 -*-
"""pythons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Xtb9bFkuD7-Pdk8zjcU-3Y7skT8OR9L
"""

print("Deepak singh")