# -*- coding: utf-8 -*-
"""normal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e43kiT3LmKOILdsQ9fbW2Oq5ywEu4d41
"""

# Right-Angled Triangle (Stars *)
# *
# * *
# * * *
# * * * *
# * * * * *
rows = 5
for i in range(1,rows+1):
  for j in range(1,i+1):
    print("*",end=" ")
  print()

# Number Triangle
# 1
# 1 2
# 1 2 3
# 1 2 3 4
# 1 2 3 4 5
rows = 5
for i in range(1,rows+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

# Reverse Number Triangle
# 1 2 3 4 5
# 1 2 3 4
# 1 2 3
# 1 2
# 1
rows = 5
for i in range(1,rows+1):
  for j in range(1,rows-i+2):
    print(j,end=" ")
  print()

# Right-Aligned Number Triangle
#         1
#       1 2
#     1 2 3
#   1 2 3 4
# 1 2 3 4 5
rows = 5
for i in range(1,rows+1):
  for space in range(rows-i):
    print(" ",end=" ")
  for num in range(1,i+1):
    print(num,end=" ")
  print()

# palindromic triangle
#         1
#       1 2 1
#     1 2 3 2 1
#   1 2 3 4 3 2 1
# 1 2 3 4 5 4 3 2 1
rows = 5
for i in range(1,rows+1):
  for space in range(rows-i):
    print(" ",end=" ")
  for num in range(1,i+1):
    print(num,end=" ")
  for num in range(i-1,0,-1):
    print(num,end=" ")
  print()

# Star Pyramid
#     *
#    * *
#   * * *
#  * * * *
# * * * * *
rows = 5

for i in range(1, rows + 1):               # Line 1 to 5
    for space in range(rows - i):         # Left spaces
        print(" ", end="")                # Space only
    for star in range(i):                 # Stars
        print("* ", end="")               # Star + space
    print()                               # New line

# Star Diamond
  #   *
  #  * *
  # * * *
  #  * *
  #   *
rows = 3
for i in range(1,rows+1):
  for spaces in range(rows-i):
    print(" ",end = "")
  for star in range(i):
    print("* ",end="")
  print()
for i in range(rows-1,0,-1):
  for space in range(rows-i):
    print(" ",end="")
  for stars in range(i):
    print("* ",end="")
  print()

#  Mixed Number-Star Triangle
# 1
# 1 *
# 1 * 2
# 1 * 2 *
# 1 * 2 * 3
rows = 5
for i in range(1,rows+1):
  num = 1
  for j in range(1,i+1):
    if j%2 == 0:
      print("*",end=" ")
    else:
      print(num,end=" ")
      num+=1
  print()

# Inverted Number Triangle
# 5 4 3 2 1
# 4 3 2 1
# 3 2 1
# 2 1
# 1
rows = 5
for i in range(rows,0,-1):
  for j in range(i,0,-1):
    print(j,end=" ")
  print()