# -*- coding: utf-8 -*-
"""datatypes.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQw92qtnlGkF3Y9pb_b53msgu4rme5qG
"""

print("Hello World")

# In Python, variables serve as named storage locations (containers) for data values. They are fundamental for storing and manipulating information within a program.
first_name = "DEEPAK"
print(f"hello {first_name}")

# integers are whole numbers. They represent complete units, like 5, -10, or 0.
age = 25
quantity = 3
num_of_students = 30

print(f"you are {age} year old")
print(f"you bought {quantity} books.")
print(f"your class consist of {num_of_students} students")

# a float (short for floating-point number) is a data type used to represent real numbers, which are numbers that have a fractional component. This means they include a decimal point, unlike integers which are whole numbers.

price = 10.34
gpa = 8.7
print(f"the price of book is {price}.")
print(f"your gpa is {gpa}.")

# a Boolean is a fundamental data type that represents one of two truth values: True or False. These values are keywords and must be capitalized as shown.
is_student = True
if is_student:
  print("you are student")
else:
  print("you are not student")

for_sale = True
if for_sale:
  print("this car is for sale.")
else:
  print("this car is not for sale.")

# none data type : None is a special constant that represents the absence of a value. It is the sole value of the NoneType data type.
a = None
print(type(a))

a = 23
b = 23.4
c = True
d = "Deepak"
e = None
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))