# -*- coding: utf-8 -*-
"""list_tuple.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cI00IzOY0IzXANMIqsifBNm5H1PlygFE
"""

#  a list is a versatile and commonly used built-in data type that serves as a collection of items.(integers,float,int,etc)
marks = [21,34.5,67,89]
print(marks)
print(len(marks))
print(marks[1])
print(marks[0])

# string are immutable
# list are mutable
student = ["karan",85,"delhi"]
student[0] = "deepak"
student[1]=12
print(student)

# List slicing in Python is a technique for extracting a portion or subsequence of elements from a list.
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Basic slicing: elements from index 2 up to (but not including) index 7
sub_list = my_list[2:7]
print(sub_list)  # Output: [2, 3, 4, 5, 6]

# Slicing from the beginning to a specific index
sub_list = my_list[:5]
print(sub_list)  # Output: [0, 1, 2, 3, 4]

# Slicing from a specific index to the end
sub_list = my_list[5:]
print(sub_list)  # Output: [5, 6, 7, 8, 9]

# Slicing with a step
sub_list = my_list[0:10:2]  # Every other element
print(sub_list)  # Output: [0, 2, 4, 6, 8]

# Reversing a list using slicing
reversed_list = my_list[::-1]
print(reversed_list) # Output: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

# Using negative indices
sub_list = my_list[-3:] # Last three elements
print(sub_list)  # Output: [7, 8, 9]

# list methods
list = [2,1,3,5,67,7]
list.append(345)
print(list)

list = [1,23,35,47,15,36,78,89]
list.sort()
print(list)

list = ["apple","orange","cherry"]
list.sort()
print(list)

list = [1,3,2,4,3,5,4,6,5]
list.sort(reverse = True)
print(list)

list = ["a","e","t","g","q"]
list.reverse()
print(list)

list = [1,3,5,7,8,2]
list.insert(1,4)
print(list)

list = [1,2,3,4,1,2,3,4,5,6,5,4,3,21]
list.remove(2)
print(list)

list = [1,2,3,4,5,6,1,2,3,4,5]
list.pop(2)
print(list)

# 2d list
groceries = ({"apple","orange","banana","coconut"},
            {"celery","carrot","spinach","cabbage"},
            {"chicken","fish","turkey"})
for collection in groceries:
  for food in collection:
    print(food,end = " ")
print()

my_pad = ((1,2,3),
          (4,5,6),
          (7,8,9),
          ("*",0,"#"))
for row in my_pad:
  for num in row:
    print(num,end=" ")
  print()

# A tuple in Python is an ordered collection of elements, similar to a list, but with a key distinction: immutability. This means that once a tuple is created, its elements cannot be changed, added, or removed.
tup = (1,2,3,4,2,1,3,4)
print(tup[3])
print(tup[0:2])
print(len(tup))
print(type(tup))
print(tup.count(2))
print(tup.index(3))
print(tup)

movies = []
mov1 = input("enter a movie: ")
mov2 = input("enter a movie: ")
mov3 = input("enter a movie: ")

movies.append(mov1)
movies.append(mov2)
movies.append(mov3)
print(movies)

list1 = [1,2,1]
list2 = [1,2,3]
copy_list1 = list1.copy()
copy_list1.reverse()
if(copy_list1==list1):
  print("palindrome")
else:
  print("not palindrome")