# -*- coding: utf-8 -*-
"""print9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZWRbdtxetocxKR4ftlHnJWLU3nq2QUf
"""

# rectangle area
length = float(input("enter the length: "))
width = float(input("enter the width: "))
area =  length * width
print(f"the area of rectangle is  {area}")

# shopping cart program
item = input("enter the item would you like to buy: ")
price = float(input("what is the price: "))
quantity = int(input("how much do you want to buy: "))
total = quantity * price
print(f"you bought {quantity} X {item}")
print(f"your total bill is {total}")

# math function
x = 3.14
y = -4
z = 5
result = round(x)
print(result)
print(abs(y))
print(pow(z,2))
print(max(x,y,z))
print(min(x,y,z))

import math
print(math.pi)
print(math.e)

import math
x = 9
result = math.sqrt(x)
print(result)

import math
x = 9.1
result = math.ceil(x)
print(result)

import math
x = 9.1
result = math.floor(x)
print(result)

# circumference of circle
import math
radius = float(input("Enter the radius: "))
circumference = 2 * math.pi * radius
print(f"the circumference of circle is {round(circumference,2)}")

# area of circle
import math
radius = float(input("Enter the radius: "))
area = math.pi * pow(radius,2)
print(f"the area of circle is {round(area,2)}")

# hypotaneous of Right angled triangle
a = float(input("enter the side a: "))
b =  float(input("enter the side b: "))
c = math.sqrt(pow(a,2)+pow(b,2))
print(f"the hypotaneous of right angled triangle is {round(c,2)}")