# -*- coding: utf-8 -*-
"""set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvbCga6nLoAuEfcB3hgqG47lTW9ASN9P
"""

# Sets in Python are an unordered collection of unique and immutable elements. They are defined using curly braces {}

# Creating a set
my_set = {1, 2, 3, 4, 2}  # Duplicates are automatically removed
print(my_set)  # Output: {1, 2, 3, 4} (order may vary)

# Adding elements
my_set.add(5)
print(my_set)  # Output: {1, 2, 3, 4, 5}

# Removing elements
my_set.remove(3)
print(my_set)  # Output: {1, 2, 4, 5}

# Set operations
set1 = {1, 2, 3}
set2 = {3, 4, 5}

union_set = set1.union(set2)
print(union_set)  # Output: {1, 2, 3, 4, 5}

intersection_set = set1.intersection(set2)
print(intersection_set)  # Output: {3}

collection = {1,2,3,4,5}
print(type(collection))

collection = {1,2,3,4,5,"hello world","hello worl",1,2}
print(len(collection))#duplicate value not allowed

collection = {}
print(type(collection))

collection = set()
print(type(collection))

info = {1,2,3,4,5,6,7,8,90}
info.add("students")
print(info)

info = {1,2,3,4,5,6,7,8,90}
info.clear()
print(info)

dictionary = {
    "table":["A peice of furniture","list of facts & furniture"],
    "cat":"a small animal"
}
print(dictionary)

subject = {"python","java,","c++","python","javascript","java","python","java","c++","c"}
print(len(subject))